Doxygen: Client Class Reference
Client Class Reference
#include <Client.hpp>
Public Member Functions
void SetClient (std::string CustomerLogin, std::string CustomerPassword)
auxiliar, chamada pelo construtor para atribuir login e senha
Client (std::string CPF, std::string Name, int Age, std::string CustomerLogin, std::string CustomerPassword)
construtor da classe, recebe informações para chamada do construtor da classe pessoa também
Client ()
construtor da classe que recebe informações do terminal
void ShowInformation () override
mostra em tela informações do cliente
int ReturnType () override
retorna o tipo da subclasse de pessoa, nesse caso, 1 para cliente
Person ()
Person (std::string CPF, int Age, std::string Name)
construtor com dados da classe
Public Member Functions inherited from Person
Person ()
Person (std::string CPF, int Age, std::string Name)
construtor com dados da classe
void getComments () override
Public Attributes
std::string CustomerLogin
std::string CustomerPassword
Public Attributes inherited from Person
int Age
std::string CPF
std::string Name
Public Attributes inherited from Members
std::string comments
Detailed Description
subclasse de pessoa, possui também informações de login de senha
Definition at line 7 of file Client.hpp.
Constructor & Destructor Documentation
Client() [1/2]
Client::Client (std::string CPF, std::string Name, int Age, std::string CustomerLogin, std::string CustomerPassword)
construtor da classe, recebe informações para chamada do construtor da classe pessoa também
Definition at line 10 of file Client.cpp.
References CustomerLogin, CustomerPassword, and SetClient().
Client() [2/2]
Client::Client ()
construtor da classe que recebe informações do terminal
Definition at line 26 of file Client.cpp.
References CustomerLogin, and CustomerPassword.
Member Function Documentation
Person() [1/2]
Person::Person
Definition at line 12 of file Person.cpp.
Person() [2/2]
Person::Person
construtor com dados da classe
Definition at line 6 of file Person.cpp.
ReturnType()
int Client::ReturnType () override virtual
retorna o tipo da subclasse de pessoa, nesse caso, 1 para cliente
Reimplemented from Person.
Definition at line 22 of file Client.cpp.
SetClient()
void Client::SetClient (std::string CustomerLogin, std::string CustomerPassword)
auxiliar, chamada pelo construtor para atribuir login e senha
Definition at line 5 of file Client.cpp.
References CustomerLogin, and CustomerPassword.
Referenced by Client().
ShowInformation()
void Client::ShowInformation () override virtual
mostra em tela informações do cliente
Reimplemented from Person.
Definition at line 15 of file Client.cpp.
References CustomerLogin, CustomerPassword, and Person::ShowInformation().
Referenced by ShowInformation().
Member Data Documentation
CustomerLogin
std::string Client::CustomerLogin
Definition at line 9 of file Client.hpp.
Referenced by Client(), SetClient(), ShowInformation(), and VerifyRegistration().
CustomerPassword
std::string Client::CustomerPassword
Definition at line 10 of file Client.hpp.
Referenced by Client(), SetClient(), ShowInformation(), and VerifyRegistration().
The documentation for this class was generated from the following files:
include/Client.hpp
src/Client.cpp