Doxygen: src/Main.cpp File Reference
Main.cpp File Reference
#include <iostream>
#include <istream>
#include <ostream>
#include <vector>
#include <string>
#include <map>
#include <cstdlib>
#include "Person.hpp"
#include "Employee.hpp"
#include "Client.hpp"
#include "Vehicles.hpp"
#include "Alocation.hpp"
#include "Agency.hpp"
#include "Exceptions.hpp"
#include "Interface.hpp"
Functions
void showComments (Members *member)
int main ()
Variables
const std::map< std::string, int > AgencysIdmap
Function Documentation
main()
int main ()
Definition at line 24 of file Main.cpp.
References AgencysIdmap, AvailableAgencys(), AvailableAlocations(), AvailableVehicles(), BackToMenu(), ClientMenu(), CommentMenu(), EmployeeMenu(), MainMenu(), Person::Name, RemoveAlocation(), showComments(), ShowInformation(), Agency::startSalesMonth(), SubMenu(), UserCreation(), ExceptionsInputs::VerifyAgencyId(), ExceptionsInputs::VerifyInputs(), VerifyRegistration(), and VerifyTypeInputs().
showComments()
void showComments (Members * member)
Definition at line 21 of file Main.cpp.
References Members::getComments().
Referenced by main().
Variable Documentation
AgencysIdmap
const std::map<std::string, int> AgencysIdmap
Initial value:
= {
  {"074",0},{"893",1},{"182",2}
}
Definition at line 17 of file Main.cpp.
Referenced by main(), and ExceptionsInputs::VerifyAgencyId().