Doxygen: ExceptionsInputs Class Reference
ExceptionsInputs Class Reference
#include <Exceptions.hpp>
Public Member Functions
ExceptionsInputs (int a, int b)
construtor da classe, atribui valores mínimo e máximo aceitados
ExceptionsInputs (std::string AUX)
Static Public Member Functions
static int VerifyInputs (int a, int b)
verifica se a entrada esta na faixa aceitada, entre a e b
static std::string VerifyExactInputs (unsigned int a, int which)
verifica se a uma entrada do tipo string tem exatamente o número de caraacteres desejados
static std::string VerifyAgencyId (std::map< std::string, int > AgencysIdmap)
verifica se o identificador da agencia é valido(esta no array de agencias)
static std::string VerifyCPF (std::vector< Person *> People)
verifica se o CPF esta cadastrado
static void VerifyBoardInputs (std::string word, unsigned int a)
Verifica se a placa foi escrita em um formato correto, numero certo de letras e etc.
static std::string VerifyOnlyNumbersInputs (std::string word)
Verifica se a entrada recebida são numeros.
static std::string VerifyBrandsInputs (std::vector< std::string > Brands)
verifica se a marca esta na lista de marcas
static std::string VerifyModelsInputs (std::string Brand, std::vector< std::vector< std::string >> Models)
verifica se o veiculo escolhido pertence à marca
Public Attributes
std::string aux
int x
int y
Detailed Description
classe dedicada a verificar entradas e lidar com exeções
Definition at line 15 of file Exceptions.hpp.
Constructor & Destructor Documentation
ExceptionsInputs() [1/2]
ExceptionsInputs::ExceptionsInputs (int a, int b)
construtor da classe, atribui valores mínimo e máximo aceitados
Definition at line 4 of file Exceptions.cpp.
References x, and y.
Referenced by VerifyAgencyId(), VerifyBoardInputs(), VerifyBrandsInputs(), VerifyCPF(), VerifyExactInputs(), VerifyInputs(), VerifyModelsInputs(), and VerifyOnlyNumbersInputs().
ExceptionsInputs() [2/2]
ExceptionsInputs::ExceptionsInputs (std::string AUX)
Definition at line 9 of file Exceptions.cpp.
References aux.
Member Function Documentation
VerifyAgencyId()
std::string ExceptionsInputs::VerifyAgencyId (std::map< std::string, int > AgencysIdmap) static
verifica se o identificador da agencia é valido(esta no array de agencias)
Definition at line 109 of file Exceptions.cpp.
References AgencysIdmap, aux, and ExceptionsInputs().
Referenced by main().
VerifyBoardInputs()
void ExceptionsInputs::VerifyBoardInputs (std::string word, unsigned int a) static
Verifica se a placa foi escrita em um formato correto, numero certo de letras e etc.
Definition at line 167 of file Exceptions.cpp.
References ExceptionsInputs().
Referenced by VerifyExactInputs().
VerifyBrandsInputs()
std::string ExceptionsInputs::VerifyBrandsInputs (std::vector< std::string > Brands) static
verifica se a marca esta na lista de marcas
Definition at line 207 of file Exceptions.cpp.
References aux, and ExceptionsInputs().
Referenced by Vehicle::Vehicle().
VerifyCPF()
std::string ExceptionsInputs::VerifyCPF (std::vector< Person *> People) static
verifica se o CPF esta cadastrado
Definition at line 129 of file Exceptions.cpp.
References aux, cpf, ExceptionsInputs(), and SearchInList().
VerifyExactInputs()
std::string ExceptionsInputs::VerifyExactInputs (unsigned int a, int which) static
verifica se a uma entrada do tipo string tem exatamente o número de caraacteres desejados
Definition at line 32 of file Exceptions.cpp.
References aux, CHASSI, cpf, ExceptionsInputs(), PLACA, RENAVAM, VerifyBoardInputs(), and VerifyOnlyNumbersInputs().
Referenced by Person::Person(), and Vehicle::Vehicle().
VerifyInputs()
int ExceptionsInputs::VerifyInputs (int a, int b) static
verifica se a entrada esta na faixa aceitada, entre a e b
Definition at line 13 of file Exceptions.cpp.
References aux, and ExceptionsInputs().
Referenced by main().
VerifyModelsInputs()
std::string ExceptionsInputs::VerifyModelsInputs (std::string Brand, std::vector< std::vector< std::string >> Models) static
verifica se o veiculo escolhido pertence à marca
Definition at line 232 of file Exceptions.cpp.
References aux, and ExceptionsInputs().
Referenced by Vehicle::Vehicle().
VerifyOnlyNumbersInputs()
std::string ExceptionsInputs::VerifyOnlyNumbersInputs (std::string word) static
Verifica se a entrada recebida são numeros.
Definition at line 186 of file Exceptions.cpp.
References aux, and ExceptionsInputs().
Referenced by VerifyExactInputs().
Member Data Documentation
aux
std::string ExceptionsInputs::aux
Definition at line 17 of file Exceptions.hpp.
Referenced by ExceptionsInputs(), VerifyAgencyId(), VerifyBrandsInputs(), VerifyCPF(), VerifyExactInputs(), VerifyInputs(), VerifyModelsInputs(), and VerifyOnlyNumbersInputs().
x
int ExceptionsInputs::x
Definition at line 18 of file Exceptions.hpp.
Referenced by ExceptionsInputs().
y
int ExceptionsInputs::y
Definition at line 19 of file Exceptions.hpp.
Referenced by ExceptionsInputs().
The documentation for this class was generated from the following files:
include/Exceptions.hpp
src/Exceptions.cpp