Doxygen: include/Interface.hpp File Reference
Interface.hpp File Reference
#include <vector>
#include "Person.hpp"
#include "Vehicles.hpp"
#include "Alocation.hpp"
#include "Agency.hpp"
#include "Client.hpp"
#include "Employee.hpp"
#include "Exceptions.hpp"
Functions
void BackToMenu ()
todas são funções auxiliares para comunicação com o usuario via terminal
void MainMenu ()
void SubMenu ()
void EmployeeMenu ()
void MenuCreation (int i)
void AvailableVehicles (std::vector< Vehicle > Cars)
void AvailableAlocations (std::vector< Alocation > Queue)
void AvailableAgencys (std::vector< Agency > Agencys)
void ShowInformation (std::vector< Person *> People)
int UserCreation (std::vector< Person *> *People)
int ClientMenu ()
int CommentMenu ()
std::vector< Alocation > RemoveAlocation (std::vector< Alocation > array)
Function Documentation
AvailableAgencys()
void AvailableAgencys (std::vector< Agency > Agencys)
Definition at line 63 of file Interface.cpp.
References Agency::getGeneralData().
Referenced by main().
AvailableAlocations()
void AvailableAlocations (std::vector< Alocation > Queue)
Definition at line 57 of file Interface.cpp.
Referenced by main().
AvailableVehicles()
void AvailableVehicles (std::vector< Vehicle > Cars)
Definition at line 50 of file Interface.cpp.
Referenced by main().
BackToMenu()
void BackToMenu ()
todas são funções auxiliares para comunicação com o usuario via terminal
Definition at line 4 of file Interface.cpp.
Referenced by main().
ClientMenu()
int ClientMenu ()
Definition at line 107 of file Interface.cpp.
Referenced by main().
CommentMenu()
int CommentMenu ()
Definition at line 116 of file Interface.cpp.
Referenced by main().
EmployeeMenu()
void EmployeeMenu ()
Definition at line 30 of file Interface.cpp.
Referenced by main().
MainMenu()
void MainMenu ()
Definition at line 12 of file Interface.cpp.
Referenced by main().
MenuCreation()
void MenuCreation (int i)
Definition at line 42 of file Interface.cpp.
Referenced by UserCreation().
RemoveAlocation()
std::vector<Alocation> RemoveAlocation (std::vector< Alocation > array)
Definition at line 114 of file Alocation.cpp.
References VerifyTypeInputs().
Referenced by main().
ShowInformation()
void ShowInformation (std::vector< Person *> People)
Definition at line 70 of file Interface.cpp.
References Client::ShowInformation(), and Employee::ShowInformation().
Referenced by main().
SubMenu()
void SubMenu ()
Definition at line 21 of file Interface.cpp.
Referenced by main().
UserCreation()
int UserCreation (std::vector< Person *> * People)
Definition at line 86 of file Interface.cpp.
References MenuCreation(), and VerifyTypeInputs().
Referenced by main().